import React, { memo } from 'react';
import { useTranslation } from 'react-i18next';
import { Accordion, AccordionContent, AccordionItem, AccordionTrigger } from '@/components/ui/accordion';

// Definição das perguntas para evitar re-renderizações desnecessárias
const faqItems = [
  {
    id: 'item-1',
    questionPtBr: 'O que é um arquivo ZPL?',
    questionEn: 'What is a ZPL file?',
    answerPtBr: 'ZPL (Zebra Programming Language) é uma linguagem usada para gerar etiquetas em impressoras Zebra. O conteúdo do arquivo ZPL define a estrutura da etiqueta (texto, QR code, códigos de barras, etc).',
    answerEn: 'ZPL (Zebra Programming Language) is a language used to generate labels for Zebra printers. The ZPL file content defines the label structure (text, QR codes, barcodes, etc).'
  },
  {
    id: 'item-2',
    questionPtBr: 'Posso usar o ZPL Easy sem impressora?',
    questionEn: 'Can I use ZPL Easy without a printer?',
    answerPtBr: 'Sim! O ZPL Easy é ideal para visualizar e testar etiquetas sem precisar da impressora física.',
    answerEn: 'Yes! ZPL Easy is ideal for viewing and testing labels without needing a physical printer.'
  },
  {
    id: 'item-3',
    questionPtBr: 'Funciona com etiquetas da Shopee ou Mercado Livre?',
    questionEn: 'Does it work with Shopee or Mercado Livre labels?',
    answerPtBr: 'Sim. Basta exportar o arquivo .txt com o código ZPL gerado pelo marketplace e fazer o upload no ZPL Easy para visualizar ou converter em PDF.',
    answerEn: 'Yes. Just export the .txt file with the ZPL code generated by the marketplace and upload it to ZPL Easy to view or convert to PDF.'
  },
  {
    id: 'item-4',
    questionPtBr: 'Preciso pagar algo para começar?',
    questionEn: 'Do I need to pay anything to start?',
    answerPtBr: 'Você pode criar uma conta gratuita para testar a conversão. Consulte nossos planos premium para maior volume.',
    answerEn: 'You can create a free account to test the conversion. Check our premium plans for higher volume.'
  },
  {
    id: 'item-5',
    questionPtBr: 'Quais plataformas de marketplace e e-commerce utilizam etiquetas ZPL?',
    questionEn: 'Which marketplace and e-commerce platforms use ZPL labels?',
    answerPtBr: 'Muitas plataformas populares de e-commerce e marketplace utilizam ou permitem a conversão de etiquetas para o formato ZPL (Zebra Programming Language), ideal para impressão em impressoras térmicas Zebra. Veja algumas:\n\nMercado Livre\n\nShopee\n\nAmazon (FBA/FBM)\n\nShopify (via apps como ShipStation e EasyPost)\n\nNuvemshop e Loja Integrada\n\nWooCommerce, Magento e PrestaShop\n\nGateways logísticos como Melhor Envio, Frenet, Intelipost, Kangu, Total Express, Loggi e Correios\n\nCom nossa ferramenta, você pode converter rapidamente etiquetas PDF para ZPL e imprimir direto em sua impressora térmica.',
    answerEn: 'Many popular e-commerce and marketplace platforms use or allow the conversion of labels to ZPL format (Zebra Programming Language), ideal for printing on Zebra thermal printers. Here are some:\n\nMercado Livre\n\nShopee\n\nAmazon (FBA/FBM)\n\nShopify (via apps like ShipStation and EasyPost)\n\nNuvemshop and Loja Integrada\n\nWooCommerce, Magento, and PrestaShop\n\nLogistics gateways like Melhor Envio, Frenet, Intelipost, Kangu, Total Express, Loggi, and Correios\n\nWith our tool, you can quickly convert PDF labels to ZPL and print directly on your thermal printer.'
  },
  {
    id: 'item-6',
    questionPtBr: 'Por que usar etiquetas ZPL em vez de PDF?',
    questionEn: 'Why use ZPL labels instead of PDF?',
    answerPtBr: 'Etiquetas no formato ZPL são ideais para impressoras térmicas, especialmente da marca Zebra. Diferente do PDF, o ZPL é leve, rápido, e compatível com sistemas de automação. Isso significa:\n\nImpressão mais rápida\n\nMenor uso de memória da impressora\n\nMaior controle do layout e da qualidade da impressão\n\nRedução de erros em grandes volumes de etiquetas\n\nSe você trabalha com alto volume de pedidos, usar ZPL pode melhorar significativamente sua operação logística.',
    answerEn: 'Labels in ZPL format are ideal for thermal printers, especially from Zebra. Unlike PDF, ZPL is lightweight, fast, and compatible with automation systems. This means:\n\nFaster printing\n\nLower printer memory usage\n\nGreater control over layout and print quality\n\nReduction of errors in large volumes of labels\n\nIf you work with high order volumes, using ZPL can significantly improve your logistics operation.'
  },
  {
    id: 'item-7',
    questionPtBr: 'Minha impressora térmica Zebra é compatível com a conversão ZPL?',
    questionEn: 'Is my Zebra thermal printer compatible with ZPL conversion?',
    answerPtBr: 'Sim! Toda impressora que suporte o padrão ZPL II (como os modelos GK420t, ZD220, ZT230, entre outros) é compatível com as etiquetas geradas por nossa ferramenta. Basta colar ou enviar o conteúdo ZPL e imprimir.\n\nVocê também pode ajustar o tamanho, margens e resolução antes de imprimir, garantindo que a etiqueta fique perfeita.',
    answerEn: 'Yes! Any printer that supports the ZPL II standard (such as models GK420t, ZD220, ZT230, among others) is compatible with the labels generated by our tool. Just paste or send the ZPL content and print.\n\nYou can also adjust the size, margins, and resolution before printing, ensuring that the label looks perfect.'
  },
  {
    id: 'item-8',
    questionPtBr: 'Como funciona a conversão de etiquetas para ZPL?',
    questionEn: 'How does label conversion to ZPL work?',
    answerPtBr: 'Com nossa ferramenta, você faz o upload de arquivos PDF, imagens ou até códigos ZPL brutos e recebe a versão otimizada para impressão. Você pode:\n\nVisualizar a etiqueta antes de imprimir\n\nAjustar configurações de tamanho e resolução\n\nSalvar etiquetas para reimpressão futura\n\nExportar lotes inteiros em ZPL\n\nIdeal para sellers de marketplaces e operadores logísticos que precisam imprimir em massa.',
    answerEn: 'With our tool, you upload PDF files, images, or even raw ZPL code and receive the optimized version for printing. You can:\n\nPreview the label before printing\n\nAdjust size and resolution settings\n\nSave labels for future reprinting\n\nExport entire batches in ZPL\n\nIdeal for marketplace sellers and logistics operators who need to print in bulk.'
  }
];

// Componente FAQ otimizado com memo para evitar renderizações desnecessárias
const FAQItem = memo(({ 
  item, 
  isPortuguese 
}: { 
  item: typeof faqItems[0], 
  isPortuguese: boolean 
}) => (
  <AccordionItem value={item.id}>
    <AccordionTrigger>
      {isPortuguese ? item.questionPtBr : item.questionEn}
    </AccordionTrigger>
    <AccordionContent>
      {isPortuguese ? item.answerPtBr : item.answerEn}
    </AccordionContent>
  </AccordionItem>
));

// Componente principal com nome mais específico para melhor profiling
export const FAQSection: React.FC = () => {
  const { i18n } = useTranslation();
  const isPortuguese = i18n.language === 'pt-BR';
  
  return (
    <section className="py-20 bg-white dark:bg-gray-900" id="faq">
      <div className="container mx-auto px-4">
        <h2 className="text-3xl md:text-4xl font-bold text-center mb-16">
          {isPortuguese ? 'Perguntas Frequentes' : 'Frequently Asked Questions'}
        </h2>
        
        <div className="max-w-3xl mx-auto">
          <Accordion type="single" collapsible className="w-full">
            {faqItems.map(item => (
              <FAQItem 
                key={item.id}
                item={item}
                isPortuguese={isPortuguese}
              />
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};
